# -*- mode: org; coding: utf-8; -*-
#+OPTIONS: \n:t
#+OPTIONS: ^:nil
#+TITLE:	Telephony
#+AUTHOR: Liu Hui
#+EMAIL: liuhui.hz@gmail.com
#+LATEX_CLASS: cn-article
#+LATEX_CLASS_OPTIONS: [9pt,a4paper]
#+LATEX_HEADER: \usepackage{geometry}
#+LATEX_HEADER: \geometry{top=2.54cm, bottom=2.54cm, left=3.17cm, right=3.17cm}
#+latex_header: \makeatletter
#+latex_header: \renewcommand{\@maketitle}{
#+latex_header: \newpage
#+latex_header: \begin{center}%
#+latex_header: {\Huge\bfseries \@title \par}%
#+latex_header: \end{center}%
#+latex_header: \par}
#+latex_header: \makeatother

#+LATEX: \newpage

* Modulation
* Passband modulation
** Analog modulation
- AM
- FM
- PM
- QAM
- SM
- SSB
** Digital modulation
- ASK
- APSK
- CPM
- FSK
- MFSK
- MSK
- OOK
- PPM
- PSK
- TCM

* DSP (Digital Signal Processing)

http://en.wikipedia.org/wiki/Waveform_viewer

#+BEGIN_SRC shell
  $ apt-cache search spectrum
  $ apt-cache search oscilloscope
  $ apt-cache search waveform
#+END_SRC

** Asterisk
http://blog.chinaunix.net/uid-7947787-id-3194117.html
http://www.aosabook.org/en/asterisk.html

** SpanDSP
SpanDSP 是一个传真处理引擎，包含了调制、发送、解调、编码等各种功能。

http://www.soft-switch.org/spandsp-modules.html

- V.17
 An ITU-T fax protocol that uses TCM modulation at 12 and 14.4 kbit/s.
- V.21
 An ITU-T recommendation for full-duplex communication between two analogue
 dial-up modems using audio frequency-shift keying modulation at 300 baud to
 carry digital data at 300 bit/s. It is a variant of the original Bell 103
 modulation format.
- V.27ter
 An ITU-T recommendation for a half-duplex modem, allowing 2400 and 4800 bit/s (PSK modulation).
- V.29
 An ITU-T recommendation for a modem, allowing 4.8 kbit/s, 7.2 kbit/s and 9.6 kbit/s transfer modes (PSK and QAM modulations).

T.30, T.4, HDLC
T1, E1
PSTN (Public Switched Telephone Network)
PLMN (Public Land Mobile Network)
误码率
