# -*- mode: org; coding: utf-8; -*-
#+OPTIONS: \n:t
#+OPTIONS: ^:nil
#+TITLE:	Abstract Algebra
#+AUTHOR: Liu Hui
#+EMAIL: liuhui.hz@gmail.com
#+LATEX_CLASS: cn-article
#+LATEX_CLASS_OPTIONS: [9pt,a4paper]
#+LATEX_HEADER: \usepackage{geometry}
#+LATEX_HEADER: \geometry{top=2.54cm, bottom=2.54cm, left=3.17cm, right=3.17cm}
#+latex_header: \makeatletter
#+latex_header: \renewcommand{\@maketitle}{
#+latex_header: \newpage
#+latex_header: \begin{center}%
#+latex_header: {\Huge\bfseries \@title \par}%
#+latex_header: \end{center}%
#+latex_header: \par}
#+latex_header: \makeatother

#+LATEX: \newpage

抽象代数，也称现代代数、近世代数，是数学的一门学科，主要研究对象是代数结构，比如群、环、域、模、向量空间和代数。
“抽象代数”这词，是为了与“初等代数”区别，后者教授公式和代数表达式的运算方式，其中有实数、复数和未知项。

https://zh.wikipedia.org/wiki/抽象代数

- 集合 set

- 群 group

- 环 ring

- 域 field

- 多项式 polynomial

- 素多项式 即约多项式
  不能分解的多项式，称作即约多项式或素多项式。
  不能表示为其他两个多项式相乘的乘积的多项式。
  只能被 $1$ 和自身整除的多项式。

- 首一多项式
  一元多项式中次数最高的项，称为首项，其系数称为该多项式的首项系数。首项系数为 $1$ 的多项式称为首一多项式。

最小多项式 首一即约多项式 分圆多项式 互反多项式 多项式值
素子域 真子域

* 集合 Set
集合（或简称集）是基本的数学概念，它是集合论的研究对象，指具有某种特定性质的事物的总体，（在最原始的集合论─朴素集合论─中的定义，集合就是“一堆东西”。）集合里的事物（“东西”），叫作元素。
如果 $x$ 是集合 $A$ 的元素，记作 $x \in A$ 或 $A \ni x$ 。

- 定义
  简单来说，所谓的一个集合，就是将数个对象归类而分成为一个或数个形态各异的大小整体。
  一般来讲，集合是具有某种特性的事物的整体，或是一些确认对象的汇集。构成集合的事物或对象称作元素或是成员。
  集合的元素可以是任何事物，可以是人，可以是物，也可以是字母或数字等。

- 符号
  元素通常用 $a, b, c, d, x$ 等小写字母来表示；而集合通常用 $A, B, C, D, X$ 等大写字母来表示。
  当元素 $a$ 属于集合 $A$ 时，记作 $a \in A$ 。
  当元素 $a$ 不属于集合 $A$ 时，记作 $a \notin A$ 。
  如何 $A$ ， $B$ 两个集合各自所包含的元素完全一样，则二者相等，记作 $A = B$ 。

- 特性
  - 无序性
    一个集合中，每个元素的地位都是相同的，元素之间是无序的。
    集合上可以定义序关系，定义了序关系后，元素之间就可以按照序关系排序。但就集合本身的特性而言，元素之间没有必然的序。
  - 互异性
    一个集合中，任何两个元素都认为是不相同的，即每个元素只能出现一次。
    有时需要对同一元素出现多次的情形进行刻画，可以使用多重集，其中的元素允许出现多次。
  - 确定性
    给定一个集合，任给一个元素，该元素或者属于或者不属于该集合，二者必居其一，不允许有模棱两可的情况出现。

- 集合的表示
  - 描述法 （ Intensional definition ）
    集合可以用文字或数字符号描述，称为描述法，比如：
      $A =$ 大于零的前三个自然数。
      $B =$ red 、white 、blue 和 green 。
  - 列举法 Extensional definition
    在大括号中列出其元素，称为列举法，比如：
      $C = \{ 1, 2, 3 \}$
      $D = \{ red, white, blue, green \}$
    对于包含很多元素的集合，元素的列举可以使用缩写。比如：
      头一千个正整数组成的集合 $\{ 1, 2, 3, \dotsc, 1000 \}$
      正偶数集合 $\{ 2, 4, 6, 8, \dots \}$
  - 集合建构式符号 Set-builder notation
    列举法可以使用在描述法中。
    $E = \{ \text{playing card suits} \}$
    更通用的形式是集合建构式符号法：
    $F = \{ n^2 - 4 : n \text{ is an integer; and } 0 \leq n \leq 19 \}$
    在这个语法中， $:$ 表示“如此”，有时使用符号 $|$ 来代替。
    $A = \{ x | x \in R, -1 < x < 1 \}$

- 集合间的关系
  - 子集 Subsets
    $A \subseteq B$ $A \supseteq B$
    $A \subsetneq B$ $A \supsetneq B$
  - 幂集 Power sets
    $P(S)$

- 集合的运算
  - 并集 Unions
    $\{ 1, 2 \} \cup \{ 1, 2 \} = \{ 1, 2 \}$
    $\{ 1, 2 \} \cup \{ 2, 3 \} = \{ 1, 2, 3 \}$
  - 交集 Intersections
    $\{ 1, 2 \} \cap \{ 1, 2 \} = \{ 1, 2 \}$
    $\{ 1, 2 \} \cap \{ 2, 3 \} = \{ 2 \}$
  - 补集（差集） Complements
    $\{ 1, 2 \} \setminus \{ 1, 2 \} = \varnothing$
    $\{ 1, 2, 3, 4 \} \setminus \{ 1, 3 \} = \{ 2, 4 \}$
  - 对称差 Symmetric difference
    表示为 $A \vartriangle B$ 、 $A \ominus B$ 或 $A \oplus B$ 。
    $A \vartriangle B = (A \setminus B) \cup (B \setminus A)$
    $\{ 1, 2, 3 \} \vartriangle \{ 3, 4 \} = \{ 1, 2, 4 \}$
  - 笛卡尔积 直积 Cartesian product
    $\{ 1, 2 \} \times \{ 1, 2 \} = \{ (1, 1), (1, 2), (2, 1), (2, 2) \}$

- 集合的元素个数
  - 有限集合
    如果集合只含有限个元素，那么这个集合可以称为有限集合。

  - 无限集合
    集合也可以有无穷多个元素，这样的集合称为无限集合。

  - 空集合
    不包含任何元素的集合，表示为 $\{\}$ 、 $\emptyset$ 或者 $\varnothing$ 。

- 特殊集合
  - $P$ 或 $\mathbb{P}$ 素数集合： $P = \{ 2, 3, 5, 7, 11, 13, 17, \dots \}$ 。
  - $N$ 或 $\mathbb{N}$ 自然数集合： $N = \{ 1, 2, 3, \dots \}$ 。
  - $Z$ 或 $\mathbb{Z}$ 整数集合： $Z = \{ \dotsc, -2, -1, 0, 1, 2, \dots \}$ 。
  - $Q$ 或 $\mathbb{Q}$ 有理数集合： $Q = \{ a/b : a, b \in Z, b \neq 0 \}$ 。
  - $R$ 或 $\mathbb{R}$ 实数集合。
  - $C$ 或 $\mathbb{C}$ 复数集合： $C = \{ a + bi : a, b \in R \}$ 。
  - $H$ 或 $\mathbb{H}$ 四元数集合： $H = \{ a + bi + cj + dk : a, b, c, d \in R \}$ 。

简单讲，一个有限（？？？）个数的集合，再能加减法运算，其结果仍在该集合内，就叫群，若能做加减、和乘除两种运算，就叫域。

* 群 Group
幂运算为重复运用群的运算符。加入运算符为普通的加法，那么幂运算就是多个加法一起使用。
** 循环群
- 定义
  由一个单独元素的一切幂次所构成的群称为循环群，该元素称为循环群的生成元。
  比如：整数关于加法构成循环群，它的生成元是 $1$ 。这里所指的元素 $1$ 的幂次是指加法运算而言。
  由于整数群是一个无限群，故这是一个无限循环群。

- 构造及性质
  设 $a$ 是循环群中的任一个元素，考虑 $a$ 的一切幂 $a^n$ ，这时可能有两种情况：
  1) $a$ 的所有幂次 $a^h(h = 0, \pm 1, \pm 2, \pm 3, \dots)$ 均不相同，这时由 $a$ 生成的群
    $G(a) = \{ \dots a^{-2}, a^{-1}, a^0, a^1, a^2 \dots \}$ 中，元素的个数无限，称为无限循环群。
  2) $a$ 的某二次幂相同，也就是存在有整数 $h$ 、 $k$ （且 $h > k$ ） 使 $a^h = a^k$ ，于是有
    $a^ha^{-k} = a^ka^{-k} = e$
    $a^{h-k} = e$
    于是，群 $G(a)$ 的元素为： $\{e, a^1, a^2, \dotsc, a^{n = h - k} = e, a^1, \dots \}$ 。
    群中的元素个数有限，所以是有限循环群。称 $a^n = e$ 的最小正整数 $n$ 为有限循环群元素 $a$ 的级。
    若为无限循环群，则 $a$ 是无限级的。在有限循环群中，有以下特点：
    - $a^0 = e, a, a^2, \dotsc, a^{n-1}$ 均不相同。
    - $a$ 为 $n$ 级元素，即 $a^n = e$ ，则 $a$ 的一切幂次生成的元素都在 $G(a) = \{ a^0 = e, a^1, a^2, \dotsc, a^{n - 1} \}$ 中。
    - 凡是循环群必是可换群。
      可换群 $G$ 中每一元素 $a$ 皆能生成一个循环群，它是 $G$ 的子集。
      如果 $a$ 是无限级元素，生成的是无线循环群。如果 $a$ 是有限级元素，则生成的是有限循环群，元素 $a$ 的级就是有限循环群的阶数。

- 有限循环群中元素级的性质
  1) 若 $a \in G$ 为 $n$ 级元素，则 $a^m = e$ 的充要条件是 $n|m$ （ $m$ 为整数）。
  2) 设 $a, b \in G$ ， $a$ 为 $n$ 级元素， $b$ 为 $m$ 级元素，且 $(n, m) = 1$ ，则 $(ab)$ 之级为 $nm$ 。
  3) 若 $a \in G$ 为 $n$ 级元素，则 $a^k$ 元素之级为 $n / (k, n)$ 。
    $n$ 阶循环群中，每一个 $n$ 级元素称为 $n$ 次单位原根。
    在 $G(a)$ 循环群中单位原根可以不止一个，只要是 $(i, n) = 1$ 的 $a^i$ 元素都是 $G(a)$ 的单位原根。
    单位原根的个数即是 $0, 1, 2, \dotsc, n - 1$ 中与 $n$ 互素的个数，可由欧拉函数 $\varphi(n)$ 求得。

** 阿贝尔群

* 环 Ring

* 域 Field
在抽象代数中，域（Field）是一种可进行加、减、乘和除（除了除以零之外）运算的代数结构。域的概念是数域以及四则运算的推广。
域是环的一种。域和一般的环的区别在于域要求它的元素（除零元素之外）可以进行除法运算，这等价于说每个非零的元素都要有乘法逆元。
同时，在现代的定义中，域中的元素关于乘法要是可交换的。简单来说，域是乘法可交换的除环。
乘法非交换的除环则称为体（Körper, corps），或者反称域（skew field）。
在比较旧的定义中，除环被称为“域”，而现代意义上的域被称为“交换域”。

域明确的满足如下性质：
- 在加法和乘法上具有封闭性。也就是说对域中的元素进行加法或乘法运算后的结果仍然是域中的元素。
  对所有属于 $F$ 的 $a, b$ ， $a + b$ 和 $a \cdot b$ 属于 $F$ （另一种说法：加法和乘法是 $F$ 上的二元运算）。
- 加法和乘法符合结合律
  对所有属于 $F$ 的 $a, b, c$ ， $(a + b) + c = a + (b + c)$ ， $(a \cdot b) \cdot c = a \cdot (b \cdot c)$ 。
- 加法和乘法符合交换律
  对所有属于 $F$ 的 $a, b$ ， $a + b = b + a$ ， $a \cdot b = b \cdot a$ 。
- 符合乘法对加法的分配律
  对所有属于 $F$ 的 $a, b, c$ ， $a \cdot (b + c) = (a \cdot b) + (a \cdot c)$ 。
- 存在加法单位元
  在 $F$ 中有称为加法单位元的元素，表示为 $0$ ，使得所有属于 $F$ 的 $a$ ， $a + 0 = a$ 。
- 存在乘法单位元
  在 $F$ 中有称为乘法单位元的元素，表示为 $1$ ，使得所有属于 $F$ 的 $a$ ， $a \cdot 1 = a$ 。
- 存在加法逆元
  对所有属于 $F$ 的 $a$ ，在 $F$ 中存在 $-a$ 使得 $a + (-a) = 0$ 。
- 存在乘法逆元
  对所有 $a \ne 0$ ，在 $F$ 中存在元素 $a^{-1}$ 使得 $a \cdot a^{-1} = 1$ 。

域中必有一个单位元 $e$ ，若作 $e + e + e + \dots$ 运算，对无限域来说，则有可能 $ne \neq 0$ ，
但在有限域中， $e + e + e + \dots + e = 0$ ，否则必成为无限域了。例如，在 $GF(2)$ 中，单位元 $e$ 为 $1$ ， $1 + 1 = 0$ 。
满足 $ne = 0$ 的最小正整数 $n$ ，称为域的特征。如果对于每一个 $n$ ，恒有 $ne \neq 0$ ，则称该域的特征为 $\infty$ 。
每个域的特征或为素数，或为 $\infty$ 。

以 $p$ 为特征的域是 $GF(p^m)$ ， $m = 1, 2, 3, \dots$ ，称 $GF(p)$ 为 $GF(p^m)$ 的基域，称 $GF(p^m)$ 为 $GF(p)$ 的扩域。
例如 $GF(2^2)$ 是 $GF(2)$ 的扩域，因为 $GF(2^2)$ 中的 $4$ 个元素都可以用 $GF(2)$ 中的两个元素 $0, 1$ 组合表示：
$GF(2^2): 00, 01, 10, 11$
$GF(2): 0, 1$

由以上性质可以得出一些最基本的推论：

  $-(a \cdot b) = (-a) \cdot b = a \cdot (-b)$
  $a \cdot 0 = 0$
  如果 $a \cdot b = 0$ ，则要么 $a = 0$ ，要么 $b = 0$ 。

- 单位元
  加法和乘法都有对应的单位元（这两个单位元一般不同，但都用符号 $e$ 表示）。
  单位元就像线性代数的单位矩阵。一个矩阵乘以单位矩阵等于本身。
  对应地，在域中的单位元有：对于加法单位元，所有元素加上单位元 $e$ ，等于其本身。对应乘法单位元，所有元素乘上单位 $e$ ，等于其本身。
- 逆元
  逆元就像数学上的倒数，两个元素互为对方的逆元。如果元素 $a$ 和 $b$ 互为加法逆元，
  那么就有 $a + b = e$ 。若互为乘法逆元，那么就有 $a \times b = e$ 。如果元素 $a$ 在域中找不到另外一个元素 $b$ ，
  使得 $a + b = e ( a \times b = e )$ ，那么 $a$ 就没有加法(乘法)逆元。
  逆元是用于除法运算的。除于一个分数就等于乘以该分数的倒数(分数的倒数就是该分数的乘法逆元)。所以要想除于某个数，可以乘以该数的逆元。

一个集合有加法单位元和乘法单位元，以及每一个元素都对应有加法逆元和乘法逆元，是成为域的必要条件。
需要注意：即使集合里面有元素 $0$ ，并且 $0$ 没有对应的乘法逆元，那么该集合也可能是一个域。因为并不要求 $0$ 有乘法逆元。

一个域的例子就是我们平时熟悉的有理数集合，相应的加法和乘法就是我们平时用的加法和乘法。
其中，加法的单位元为 $0$ ，有理数 $a$ 的加法逆元就是其相反数。因为 $a + (-a) = 0$ (单位元)。乘法的单位元为 $1$ ，
$a$ 的乘法逆元是其倒数。因为 $a \times \frac{1}{a} = 1$ 。注意这里的元素 $0$ 并没有乘法逆元。

** 剩余类域 剩余系 完全剩余系

** 有理数域
** 实数域
** 有限域 （ Finite Field ）、伽罗瓦域 GF （ Galois Field ）
有限域是一个包含有限数量元素的域（ field ）。如同任何一个域，有限域是一个集合，其加减乘除操作定义和满足特定基本规则。
有限域一个最常见的例子是整数取素数模。

有限域内元素的数目称为它的阶（ order ），一个阶为 $q$ 的有限域存在的条件是单且仅单 $q$ 是一个素数的幂 $p^k$ ( $p$ 是素数， $k$ 为正整数)。

所有给定阶的有限域都是同构的（ isomorphic ）。

In a field of order $p^k$, adding $p$ copies of any element always results in zero; that is, the characteristic of the field is $p$.
一个阶为 $p^k$ 的域内，也就是说，域的特征（ characteristic ） 为 $p$ 。

一个阶为 $q$ 的有限域的所有 $q$ 个元素都是多项式( polynomial ) $X^q - X$ 的根（ root ）。

一个有限域的所有非零元素构成了一个乘法群（ multiplicative group ），这个群是循环群（ cyclic group ），因此，
所有非零元素都可以表示为一个称为域的本原（ primitive element ）的单一元素的幂（通常一个域有多个本原）。

$GF(q)$ 的特征为 $q$ ，对于域中每一个非 $0$ 元素 $a$ ，均有 $q \cdot a = 0$ 。

对于每一个 $a \neq 0$ ， $a \in GF(q)$ ，满足 $na = 0$ 的最小正整数 $n$ ，称为域元素 $a$ 的周期。
域中一切非 $0$ 元素的周期都是相同的，等于域的特征。
域的特性（或元素的周期）说明了域中加法运算的循环性，而域中元素的级说明了域中乘法运算的循环性。

任何 $q$ 阶有限域中都能找到一个生成元素 $a$ ，它的级为 $q - 1$ ，能生成域中所有 $q - 1$ 个非 $0$ 元素，
从而组成一个循环乘群 $G(a): 1, a, a^2, \dotsc, a^{q - 2}, a^{q - 1} = 1$ 。

若 $a$ 为域 $GF(q)$ 中的 $n$ 级元素，则称 $a$ 为 $n$ 次单位原根。
若在 $GF(q)$ 中，某一元素 $a$ 的级为 $q - 1$ ，则称 $a$ 为本原域元素。
由于 $GF(q)$ 中所有 $q - 1$ 个非 $0$ 元素组成一个乘群，因此本原域元素 $a$ 能生成这个乘群，与循环群中的定义类似，显然有 $a^{q - 1} = e$ 。

在 $GF(q)$ 中，每一个非 $0$ 元素均满足 $x^{q - 1} = 1$ ，即都是方程 $x^{q - 1} - 1 = 0$ 的根。
反之， $x^{q - 1} - 1 = 0$ 的根必在 $GF(q)$ 中。

在 $GF(q)$ 中 $n$ 级元素 $a$ 生成的循环群 $G(a)$ ，一定是方程 $x^n - 1 = 0$ 的根。

$GF(q)$ 中必有本原域元素存在。

设 $a$ 是 $GF(q)$ 的 $n$ 级元素，则由循环群的性质可知， $G(a) = \{1, a, a^2, \dotsc, a^{n-1} \}$ 是一个由 $a$ 生成的循环子群。
方程 $x^n - 1 = 0$ 的全部根，就是 $GF(q)$ 内的 $G(a)$ 子群的元素。因而：
$x^n - 1 = (x - a^0)(x - a)(x - a^2)\dots(x - a^{n - 1}) = \coprod_{i = 0}^{n - 1}{(x - a^i)}$

*** 有限域 $GF(p)$
$GF(p)$ $F_p$
在密码学中，有限域 $GF(p)$ 是一个很重要的域，其中 $p$ 为素数，只有当 $p$ 为素数时，才能保证集合中的所有的元素都有加法和乘法逆元（ 0 除外）。
简单来说， $GF(p)$ 就是 $\pmod p$ ，因为一个数 $\pmod p$ 后，结果在 $[ 0, p-1 ]$ 之间。对于元素 $a$ 和 $b$ ，
那么 $(a + b) \pmod p$ 和 $(a * b) \pmod p$ ，其结果都是域中的元素。
$GF(p)$ 里面的加法和乘法都是平时用的加法和乘法。 $GF(p)$ 的加法和乘法单位元分别是 $0$ 和 $1$ 。

*** 有限域 $GF(p^n)$

*** 本原多项式 （ Primitive Polynomial ）
