# -*- mode: org; coding: utf-8; -*-
#+OPTIONS: \n:t
#+OPTIONS: ^:nil
#+TITLE:	Communication
#+AUTHOR: Liu Hui
#+EMAIL: liuhui.hz@gmail.com
#+LATEX_CLASS: cn-article
#+LATEX_CLASS_OPTIONS: [9pt,a4paper]
#+LATEX_HEADER: \usepackage{geometry}
#+LATEX_HEADER: \geometry{top=2.54cm, bottom=2.54cm, left=3.17cm, right=3.17cm}
#+latex_header: \makeatletter
#+latex_header: \renewcommand{\@maketitle}{
#+latex_header: \newpage
#+latex_header: \begin{center}%
#+latex_header: {\Huge\bfseries \@title \par}%
#+latex_header: \end{center}%
#+latex_header: \par}
#+latex_header: \makeatother

#+LATEX: \newpage

- 传输介质
  数据传输总是通过某种传输媒体在发送设备和接收设备之间进行。传输媒体可以划分为导线的或无导线的两类。
  无论属于哪一种类别，通信都以电磁波的形式发生。
  使用导线媒体，波的传播被限制到一条物理通路。导线媒体的例子有双绞线、同轴电缆和光导纤维。
  无导线媒体提供发射电磁波的手段，但不约束传播的通路。无导线传播的例子有通过空气、真空和海水的通信。
  常用的无线通信系统有无线电、微波、卫星、红外线、激光等等。
  - 有线介质
    - 双绞线
      - 屏蔽双绞线 STP(IBM)
      - 非屏蔽双绞线 UTP(EIA/TIA)
    - 同轴电缆
    - 光纤
  - 无线介质

- 波
  - 横波 Transverse wave
   介质振动方向和波行进方向垂直的一种波。
  - 纵波 Longitudinal wave
   指在传播介质中质点的振动方向与波的传播方向平行的一类波。
  - 波峰 crest
  - 波谷 trough
  - 波长 wavelength
   波长是一个物理学的名词，指在某一固定的频率里，沿着波的传播方向、在波的图形中，离平衡位置的“位移”与“时间”皆相同的两个质点之间的最短距离。
   在物理学，波长普遍使用希腊字母 λ 来表示。
   在横波中，波长是指相邻两个有相同相位的点的距离，通常是相邻的波峰、波谷或对应的过零点。在纵波中，波长是指相邻两个密部或疏部之间的距离。
   波长 λ 与频率 $\nu$ 成反比关系。频率就是某一固定时间内，通过某一指定地方的波数目。以下方程表达了波长与频率的关系：
   $\lambda = \frac{\upsilon_\omega}{\nu}$
    + $\upsilon_\omega$ 波的相速度
  - 波幅 振幅 amplitude
   在波动或振动中距离平衡位置或静止位置的最大位移。
  - 周期
   指的是完成往复运动一次所需的时间，物理学上通常以 T 表示，单位为 s 。
   周期为频率（物理学上通常以 f 表示）的倒数： $T = \frac{1}{f}$
  - 频率
   单位时间内某事件重复发生的次数，在物理学中通常以符号 f 或 $\nu$ 表示。采用国际单位制，其单位为赫兹（英语： Hertz ，简写为 Hz ）。
  - 角频率
   在物理学（特别是力学和电子工程）中，角频率 ω 有时也叫做角速度标量，是对旋转快慢的度量，它是角速度矢量 $\vec{\omega}$ 的模。
   角频率的国际单位是弧度每秒。由于弧度是无量纲的，所以角频率的量纲为 $T^{-1}$ 。
   因为旋转一周的弧度是 2π ，所以
   $\omega = \frac{2\pi}{T} = 2\pi f = \upsilon/r = \frac{ds}{dt}\cdot\frac{1}{r} = \frac{d\theta}{dt}$
    + ω 是角频率（单位为弧度每秒）
    + T 是周期（单位为秒）
    + f 是频率（单位为赫兹）
    + v 是绕轴旋转的线速度（单位为米每秒）
    + r 是旋转的半径（单位为米）
  - 相速度
   波的相速度或相位速度 (phase velocity) ，或简称相速，是指波的相位在空间中传递的速度，换句话说，波的任一频率成分所具有的相位即以此速度传递。
  - 群速度
   波的群速度 (group velocity) ，或简称群速，是指波振幅外形上的变化（称为波的“调变”或“波包”）在空间中所传递的速度。

- 调制
 http://en.wikipedia.org/wiki/Modulation
  - 模拟调制
    - 幅度调制（调幅）(Amplitude modulation, AM）
      - 双边带调制(Double-sideband modulation, DSB）
        - Double-sideband modulation with carrier (DSB-WC) (used on the AM radio broadcasting band)
        - Double-sideband suppressed-carrier transmission (DSB-SC)
        - Double-sideband reduced carrier transmission (DSB-RC)
      - 单边带调制（Single-sideband modulation, SSB or SSB-AM）
        - SSB with carrier (SSB-WC)
        - SSB suppressed carrier modulation (SSB-SC)
      - 残余边带调制（Vestigial-sideband modulation, VSB or VSB-AM）
      - Quadrature amplitude modulation (QAM)
    - 角度调制（Angle modulation）
      - 相位调制（调相）（Phase modulation, PM）
      - 频率调制（调频）(Frequency modulation, FM）
  - 数字调制
    - 幅度偏移调制（Amplitude-shift keying, ASK）and its most common form, on-off keying（OOK）
    - 相位偏移调制（Phase-shift keying, PSK）
    - 正交幅度调制（Quadrature amplitude modulation, QAM）结合PSK与ASK的方式来作调制
    - 频率偏移调制（Frequency-shift keying, FSK
    - audio frequency-shift keying (AFSK)
    - Minimum-shift keying（MSK）
    - Gaussian minimum-shift keying（GMSK）
    - 连续相位调制（Continuous phase modulation, CPM）
    - 正交频分复用（Orthogonal frequency division multiplexing, OFDM）modulation, also known as discrete multitone (DMT)
    - Wavelet modulation
    - Trellis coded modulation (TCM) also known as trellis modulation
  - 脉冲调制
    - 脉冲编码调制 Pulse-code modulation（PCM，Analog-over-digital）
    - 脉冲宽度调制 Pulse-width modulation（PWM，Analog-over-analog）
    - 脉冲幅度调制 Pulse-amplitude modulation（PAM，Analog-over-analog）
    - 脉冲位置（相位和频率）调制 Pulse-position modulation(PPM，Analog-over-analog）
    - 脉冲密度调制 Pulse-density modulation（PDM，Analog-over-analog）
    - 三角积分调制 Sigma-delta modulation（∑Δ，Analog-over-digital）
- digital mode
- 解调
- 信号
- 载波（Carrier signal, Carrier wave）
 指被调制以传输信号的波形，一般为正弦波。一般要求正弦载波的频率远远高于调制信号的带宽，否则会发生混叠，使传输信号失真。
- 载波频率
- 码元 数字脉冲
- 波特率（Baud）即调制速率
 波特率，又称调制速率、传符号率（符号又称单位码元），指单位时间内载波参数变化的次数，可以以波形每秒的振荡数来衡量，是信号传输速率的度量。
 在电子通信领域，波特率（Baud）即调制速率，指的是有效数据信号调制载波的速率，即单位时间内载波调制状态变化的次数。
 In telecommunication and electronics, baud (/ˈbɔːd/, unit symbol Bd) is the
 unit for symbol rate or modulation rate in symbols per second or pulses per
 second. It is the number of distinct symbol changes (signaling events) made to
 the transmission medium per second in a digitally modulated signal or a line
 code.
 N 每个码元负载的信息量， R 秒比特率，包括信道编码。
 $f_s = \frac{R}{N}$
 $R = f_s \log_2(M)$
- 比特率（Bit rate）
- 两相调制 四相调制
- 载波频率 基波频率 调制比
- 信道
- 时隙
- 带宽（Bandwidth）
 带宽，又叫频宽，是数据的传输能力，指单位时间内能够传输的比特数。高带宽意味着高能力。
 数字设备中带宽用 bps（b/s）表示，即每秒最高可以传输的位数。
 模拟设备中带宽用 Hz 表示，即每秒传送的信号周期数。
 通常描述带宽时省略单位，如 10M 实质是 10M b/s 。
 带宽计算公式为：带宽 = 时钟频率 * 总线位数 / 8。
 电子学上的带宽则指电路可以保持稳定工作的频率范围。

 信号在频域里最高的那个频率分量就被称为信号的带宽。

 - 常见信号的带宽
   | 语音信号   | 300 Hz ~ 3400 Hz                                                       |
   | 音乐信号   | 20 Hz ~ 20 KHz                                                         |
   | 电视信号   | ~ 4 MHz                                                                |
   | 单脉冲信号 | 无穷大                                                                 |
   | 二进制信号 | 一般情况下，其带宽依赖于 "0" ， "1" 序列的顺序以及具体的数字编码方式。 |

- 信道带宽
- 信噪比
- 时域
- 频域
- 采样
- 时域采样
- 采样窗口
- 相干采样
- 非相干采样
- 频谱泄漏
- 窗函数
- 混叠 (Aliasing)
 在信号频谱上可称作叠频；在影像上可称作叠影，主要来自于对连续时间信号作取样以数字化时，取样频率低于两倍奈奎斯特频率。
 在统计、信号处理和相关领域中，混叠是指取样信号被还原成连续信号时产生彼此交叠而失真的现象。
 当混叠发生时，原始信号无法从取样信号还原。而混叠可能发生在时域上，称做时间混叠，或是发生在频域上，被称作空间混叠。
- 频谱
- 频谱混叠
- 频分多址(frequency division multiple access, FDMA)
- 多址方式
- TDMA
- CDMA
- GSM
- GPRS

- Packet radio 封包无线电

- MARK
- SPACE

- BER (Bit-Error Rate) 误码率

- 2FSK
  BFSK (Binary Frequency Shift Keying)
- AFSK
- CPFSK Continuous-Phase Frequency Shift Keying 连续相位频移键控
- DPFSK 离散相位频移键控

- 包络 envelope
- 包络恒定
- 非线性放大器

- Zero crossing 过零检测

- PLL Phase Locked Loop 锁相回路或锁相环

- SSB 单边带
  - USB 上边带
  - LSB 下边带
- DSB 双边带

- baseband
- passband
- 低通
- 高通
- 带通 band-pass
- 带阻
- 信噪比 信号噪声功率比

- 截止频率 cutoff frequency
 https://en.wikipedia.org/wiki/Cutoff_frequency
 在物理学和电机工程学中，一个系统的输出信号的能量通常随输入信号的频率发生变化（频率响应）。
 截止频率（英语：Cutoff frequency）是指一个系统的输出信号能量开始大幅下降（在带阻滤波器中为大幅上升）的边界频率。

 信道带宽是指该系统不失真传输信号的频率范围。
 信道的带宽决定对其通过信号的带宽，因而对于有限带宽信道必须限制信号的带宽，即限制信号的数据传输率，否则输出信号就会畸变。
 信号在经过信道时其中某个频率分量的振幅衰减到原来的 0.707 （即信号的能量衰减到原来的一半）时所对应的频率称为信道的截止频率 $f_c$ 。
 即低通信道的有效带宽（ 0 ~ $f_c$ ）。
 任何信道都有 $f_c$ ，信道的截止频率或带宽是由其固有的物理特性决定的。

- 频率响应
 简称频响，英文名称是Frequency Response，在电子学上用来描述一台仪器对于不同频率的信号的处理能力的差异。

- 带宽和截止频率
 截止频率 ωc 规定为幅频特性 |G(jω)| 达到 0.7M0 并继续下降时的临界频率。对应的频率范围 0 ≤ ω ≤ ωc 称为带宽。
 截止频率的含义是：系统对频率高于ωc的信号分量具有过滤的功能，而频率低于ωc的信号分量则可直接通过或略有衰减。
 从复现输入信号的角度来说，常要求带宽大一些，它相应于较小的上升时间和较快的响应速度。
 但从抑制高频噪声的角度来看，则带宽不宜太大。因此确定带宽需要全面考虑。

- 波形 (waveform)
 http://en.wikipedia.org/wiki/Waveform
 http://en.wikipedia.org/wiki/Waveform_viewer

- 曼彻斯特编码
 曼彻斯特编码（Manchester Encoding），也叫做相位编码（ Phase Encode，简写PE），
 是一个同步时钟编码技术，被物理层使用来编码一个同步位流的时钟和数据。它在以太网
 媒介系统中的应用属于数据通信中的两种位同步方法里的自同步法（另一种是外同步法）
 ，即接收方利用包含有同步信号的特殊编码从信号自身提取同步信号来锁定自己的时钟脉
 冲频率，达到同步目的。

- 周期信号 (periodic signal)
 瞬时幅值随时间重复变化的信号称为周期信号。一般表达式为：
 $x(t) = x(t+kT), $
 t 表示时间， T 表示周期。
 周期信号分为：均匀性和非均匀性信号。
 在非正弦的周期性振荡中，包含基波和谐波。和该振荡周期相等的正弦波分量称为基波分量。
 相应于这个周期的频率称为基波频率。频率等于基波频率的整倍数的正弦波分量称为谐波。
 一个周期信号可以通过傅里叶变换分解为直流分量 c0 和不同频率的正弦信号的线性叠加：
 $f(t) = c_0 + \sum\limits_{m=1}^{\infty}c_m\sin(m\omega t + \varphi_m)$
 $c_m$ 表示 m 次谐波的幅值，其角频率为 $m\omega$ ，初始相位为 $\varphi_m$ ，其有效值为 $\frac{c_m}{\sqrt{2}}$
 $\frac{\omega}{2\pi}$ 为基波分量的频率，称为基波频率，基波分量的频率等于交流信号的频率。而 m 次谐波的频率为基波频率的整数倍（ m 倍）。
- 基波
 在复杂的周期性振荡中,包含基波和谐波。
 和该振荡最长周期相等的正弦波分量称为基波。
 相应于这个周期的频率称为基本频率 (fundamental frequency) 。
 频率等于基本频率的整倍数的正弦波分量称为谐波。
- 谐波 (Harmonic)
 谐波是一个数学或物理学概念，是指周期函数或周期性的波形中能用常数、与原函数的最小正周期相同的正弦函数和余弦函数的线性组合表达的部分。
- 直流分量 0 次谐波
- 基波分量 1 次谐波
 复合波的最低频率分量。

- 蝶形变换

- 傅里叶级数 (Fourier series)
- 傅里叶变换 (Fourier transform)
  vs ?拉普拉斯变换 ?z 变换
  - 离散傅里叶变换 (Discrete Fourier Transform, DFT)
  - 短时傅里叶变换

- 小波变换 (Wavelet transform)
  - 离散小波变换（DWT）
  - 连续小波转换（CWT）

- 听觉
  - 频率理论
  - 共鸣理论
  - 行波理论
  - 神经齐射理论

- CRC (Cyclic redundancy check) 循环冗余校验
  CRC-1 奇偶校验

- 串行通讯方式
  - 同步位 起始位 停止位 数据位 奇偶校验位(Parity bit) 位时间(bit times)
    停止位，其实是停止周期（ stop period ）。让接受端处理数据及重新同步。
    #+BEGIN_QUOTE
    1.5 位停止位
    这个是表示时间上的宽度，每 1 位的发送时间叫位时间，是波特率的倒数，那么 1.5 位停止位就是说这个停止位发送的时间是 1.5 倍的位时间。
    #+END_QUOTE

  - 同步
    https://en.wikipedia.org/wiki/Synchronous_serial_communication

  - 异步
    https://en.wikipedia.org/wiki/Asynchronous_serial_communication

- Baudot code

- 奈奎斯特抽样定理

- 数字通信带宽占用比模拟通信带宽占用大

- 脉冲编码调制 PCM（Pulse-code modulation）
  脉冲编码调制就是把一个时间连续，取值连续的模拟信号变换成时间离散，取值离散的数字信号后在信道中传输。
  脉冲编码调制就是对模拟信号先抽样，再对样值幅度量化，编码的过程。
  - 抽样
    就是对模拟信号进行周期性扫描，把时间上连续的信号变成时间上离散的信号，抽样必须遵循奈奎斯特抽样定理。
    该模拟信号经过抽样后还应当包含原信号中所有信息，也就是说能无失真的恢复原模拟信号。
    它的抽样速率的下限是由抽样定理确定的。抽样速率采用 8 Kbit/s 。
  - 量化
    就是把经过抽样得到的瞬时值将其幅度离散，即用一组规定的电平，把瞬时抽样值用最接近的电平值来表示,通常是用二进制表示。
    为解决均匀量化时小信号量化误差大，音质差的问题，在实际中采用不均匀选取量化间隔的非线性量化方法，
    即量化特性在小信号时分层密，量化间隔小，而在大信号时分层疏，量化间隔大。
    在实际中使用的是两种对数形式的压缩特性： A 律和 U 律， A 律编码主要用于 30/32 路一次群系统， U 律编码主要用于 24 路一次群系统。
    A 律 PCM 用于欧洲和中国， U 律 PCM 用于北美和日本。
  - 编码
    就是用一组二进制码组来表示每一个有固定电平的量化值。
    然而，实际上量化是在编码过程中同时完成的，故编码过程也称为模/数变换，可记作 A/D 。

  量化方法
  - 线性
  - 非线性
    - A律 A-law
      经过压扩后的非均匀量化
    - u律 μ-law
      经过压扩后的均匀量化

* Modulation
* Passband modulation
** Analog modulation
- AM
- FM
- PM
- QAM
- SM
- SSB
** Digital modulation
- ASK
- APSK
- CPM
- FSK
- MFSK
- MSK
- OOK (On-Off Keying) 2ASK
- PPM
- PSK
- TCM

* DSP (Digital Signal Processing)

http://en.wikipedia.org/wiki/Waveform_viewer

#+BEGIN_SRC shell
  $ apt-cache search spectrum
  $ apt-cache search oscilloscope
  $ apt-cache search waveform
#+END_SRC

** Asterisk
http://blog.chinaunix.net/uid-7947787-id-3194117.html
http://www.aosabook.org/en/asterisk.html

** SpanDSP
SpanDSP 是一个传真处理引擎，包含了调制、发送、解调、编码等各种功能。

http://www.soft-switch.org/spandsp-modules.html

- V.17
 An ITU-T fax protocol that uses TCM modulation at 12 and 14.4 kbit/s.
- V.21
 An ITU-T recommendation for full-duplex communication between two analogue
 dial-up modems using audio frequency-shift keying modulation at 300 baud to
 carry digital data at 300 bit/s. It is a variant of the original Bell 103
 modulation format.
- V.27ter
 An ITU-T recommendation for a half-duplex modem, allowing 2400 and 4800 bit/s (PSK modulation).
- V.29
 An ITU-T recommendation for a modem, allowing 4.8 kbit/s, 7.2 kbit/s and 9.6 kbit/s transfer modes (PSK and QAM modulations).

T.30, T.4, HDLC
T1, E1
PSTN (Public Switched Telephone Network)
PLMN (Public Land Mobile Network)

mode-line

误码率(bert)

分贝

阻抗
在具有电阻、电感和电容的电路里，对电路中的电流所起的阻碍作用叫做阻抗。
阻抗常用 Z 表示，是一个复数，实际称为电阻，虚称为电抗。
其中电容在电路中对交流电所起的阻碍作用称为容抗，
电感在电路中对交流电所起的阻碍作用称为感抗，
电容和电感在电路中对交流电引起的阻碍作用总称为电抗。
阻抗的单位是欧姆。阻抗的概念不仅存在与电路中，在力学的振动系统中也有涉及。

电功率
物理学名词，电流在单位时间内做的功叫做电功率。
是用来表示消耗电能的快慢的物理量，用 P 表示，它的单位是瓦特（ Watt ），简称"瓦"，符号是 W 。

电平
逻辑电平
CMOS
TTL

dBm dBmW
https://en.wikipedia.org/wiki/DBm

绝对功率电平
通常是以 1mw 为基准功率，相对与 1mw 的功率电平称之为绝对功率电平，其电平符号为 dBm 。
比如 20W 的功率输入，就可以认为输入电平是 10*log（20W/1mW) ,即 43dBm 。
零电平功率，零电平电压和零电平电流

相对功率电平
不使用固定的功率作为比较的基准，而是以参考点的信号功率为比较对象，这样求得的电平称为相对功率电平，其电平符号为dBr。

传送电平点 TLP transmission level point

参考电平

dBm0
含义同 dBm 类似，只是相对于零 TLP 点的 dBm 值。
相对零参考电平点的绝对参考电平。
dbov

动态范围 (Dynamic range)

直接数字式频率合成器（Direct Digital Synthesizer, DDS）
spandsp/dds.h

DDS int
src/dds_int.c

DDS float
src/dds_float.c
