# -*- mode: org; coding: utf-8; -*-
#+OPTIONS: \n:t
#+OPTIONS: ^:nil
#+TITLE:	Communication
#+AUTHOR: Liu Hui
#+EMAIL: liuhui.hz@gmail.com
#+LATEX_CLASS: cn-article
#+LATEX_CLASS_OPTIONS: [9pt,a4paper]
#+LATEX_HEADER: \usepackage{geometry}
#+LATEX_HEADER: \geometry{top=2.54cm, bottom=2.54cm, left=3.17cm, right=3.17cm}
#+latex_header: \makeatletter
#+latex_header: \renewcommand{\@maketitle}{
#+latex_header: \newpage
#+latex_header: \begin{center}%
#+latex_header: {\Huge\bfseries \@title \par}%
#+latex_header: \end{center}%
#+latex_header: \par}
#+latex_header: \makeatother

#+LATEX: \newpage

- 调制
 http://en.wikipedia.org/wiki/Modulation
  - 模拟调制
    - 幅度调制（调幅）(Amplitude modulation, AM）
      - 双边带调制(Double-sideband modulation, DSB）
        - Double-sideband modulation with carrier (DSB-WC) (used on the AM radio broadcasting band)
        - Double-sideband suppressed-carrier transmission (DSB-SC)
        - Double-sideband reduced carrier transmission (DSB-RC)
      - 单边带调制（Single-sideband modulation, SSB or SSB-AM）
        - SSB with carrier (SSB-WC)
        - SSB suppressed carrier modulation (SSB-SC)
      - 残余边带调制（Vestigial-sideband modulation, VSB or VSB-AM）
      - Quadrature amplitude modulation (QAM)
    - 角度调制（Angle modulation）
      - 相位调制（调相）（Phase modulation, PM）
      - 频率调制（调频）(Frequency modulation, FM）
  - 数字调制
    - 幅度偏移调制（Amplitude-shift keying, ASK）and its most common form, on-off keying（OOK）
    - 相位偏移调制（Phase-shift keying, PSK）
    - 正交幅度调制（Quadrature amplitude modulation, QAM）结合PSK与ASK的方式来作调制
    - 频率偏移调制（Frequency-shift keying, FSK
    - audio frequency-shift keying (AFSK)
    - Minimum-shift keying（MSK）
    - Gaussian minimum-shift keying（GMSK）
    - 连续相位调制（Continuous phase modulation, CPM）
    - 正交频分复用（Orthogonal frequency division multiplexing, OFDM）modulation, also known as discrete multitone (DMT)
    - Wavelet modulation
    - Trellis coded modulation (TCM) also known as trellis modulation
  - 脉冲调制
    - 脉冲编码调制 Pulse-code modulation（PCM，Analog-over-digital）
    - 脉冲宽度调制 Pulse-width modulation（PWM，Analog-over-analog）
    - 脉冲幅度调制 Pulse-amplitude modulation（PAM，Analog-over-analog）
    - 脉冲位置（相位和频率）调制 Pulse-position modulation(PPM，Analog-over-analog）
    - 脉冲密度调制 Pulse-density modulation（PDM，Analog-over-analog）
    - 三角积分调制 Sigma-delta modulation（∑Δ，Analog-over-digital）
- 解调
- 信号
- 载波（Carrier signal, Carrier wave）
 指被调制以传输信号的波形，一般为正弦波。一般要求正弦载波的频率远远高于调制信号的带宽，否则会发生混叠，使传输信号失真。
- 载波频率
- 码元 数字脉冲
- 波特率（Baud）即调制速率
 波特率，又称调制速率、传符号率（符号又称单位码元），指单位时间内载波参数变化的次数，可以以波形每秒的振荡数来衡量，是信号传输速率的度量。
 In telecommunication and electronics, baud (/ˈbɔːd/, unit symbol Bd) is the
 unit for symbol rate or modulation rate in symbols per second or pulses per
 second. It is the number of distinct symbol changes (signaling events) made to
 the transmission medium per second in a digitally modulated signal or a line
 code.
 N 每个码元负载的信息量， R 秒比特率，包括信道编码。
 $f_s = \frac{R}{N}$
 $R = f_s \log_2(M)$
- 比特率（Bit rate）
- 两相调制 四相调制
- 信道
- 时隙
- 带宽（Bandwidth）
 带宽，又叫频宽，是数据的传输能力，指单位时间内能够传输的比特数。高带宽意味着高能力。
 数字设备中带宽用 bps（b/s）表示，即每秒最高可以传输的位数。
 模拟设备中带宽用 Hz 表示，即每秒传送的信号周期数。
 通常描述带宽时省略单位，如 10M 实质是 10M b/s 。
 带宽计算公式为：带宽 = 时钟频率 * 总线位数 / 8。
 电子学上的带宽则指电路可以保持稳定工作的频率范围。
- 信道带宽
- 信噪比
- 时域
- 频域
- 采样
- 时域采样
- 频谱
- 频谱混叠
- 频分多址(frequency division multiple access, FDMA)
- 多址方式
- TDMA
- CDMA
- GSM
- GPRS

- baseband
- passband
- 低通
- 带通 band-pass
- 信噪比 信号噪声功率比

- 曼彻斯特编码
 曼彻斯特编码（Manchester Encoding），也叫做相位编码（ Phase Encode，简写PE），
 是一个同步时钟编码技术，被物理层使用来编码一个同步位流的时钟和数据。它在以太网
 媒介系统中的应用属于数据通信中的两种位同步方法里的自同步法（另一种是外同步法）
 ，即接收方利用包含有同步信号的特殊编码从信号自身提取同步信号来锁定自己的时钟脉
 冲频率，达到同步目的。

* Modulation
* Passband modulation
** Analog modulation
- AM
- FM
- PM
- QAM
- SM
- SSB
** Digital modulation
- ASK
- APSK
- CPM
- FSK
- MFSK
- MSK
- OOK
- PPM
- PSK
- TCM

* DSP (Digital Signal Processing)

http://en.wikipedia.org/wiki/Waveform_viewer

#+BEGIN_SRC shell
  $ apt-cache search spectrum
  $ apt-cache search oscilloscope
  $ apt-cache search waveform
#+END_SRC

** Asterisk
http://blog.chinaunix.net/uid-7947787-id-3194117.html
http://www.aosabook.org/en/asterisk.html

** SpanDSP
SpanDSP 是一个传真处理引擎，包含了调制、发送、解调、编码等各种功能。

http://www.soft-switch.org/spandsp-modules.html

- V.17
 An ITU-T fax protocol that uses TCM modulation at 12 and 14.4 kbit/s.
- V.21
 An ITU-T recommendation for full-duplex communication between two analogue
 dial-up modems using audio frequency-shift keying modulation at 300 baud to
 carry digital data at 300 bit/s. It is a variant of the original Bell 103
 modulation format.
- V.27ter
 An ITU-T recommendation for a half-duplex modem, allowing 2400 and 4800 bit/s (PSK modulation).
- V.29
 An ITU-T recommendation for a modem, allowing 4.8 kbit/s, 7.2 kbit/s and 9.6 kbit/s transfer modes (PSK and QAM modulations).

T.30, T.4, HDLC
T1, E1
PSTN (Public Switched Telephone Network)
PLMN (Public Land Mobile Network)
误码率
