# -*- mode: org; coding: utf-8; -*-
#+OPTIONS: \n:t
#+OPTIONS: ^:nil
#+TITLE:	Emacs 之 Helm
#+AUTHOR: Liu Hui
#+EMAIL: hliu@arcsoft.com
#+LATEX_CLASS: cn-article
#+LATEX_CLASS_OPTIONS: [9pt,a4paper]
#+LATEX_HEADER: \usepackage{geometry}
#+LATEX_HEADER: \geometry{top=2.54cm, bottom=2.54cm, left=3.17cm, right=3.17cm}
#+latex_header: \makeatletter
#+latex_header: \renewcommand{\@maketitle}{
#+latex_header: \newpage
#+latex_header: \begin{center}%
#+latex_header: {\Huge\bfseries \@title \par}%
#+latex_header: \end{center}%
#+latex_header: \par}
#+latex_header: \makeatother

#+LATEX: \newpage

* 概述
Helm 是 Emacs 中的一个增量补全和精炼选择项的框架. 在 Emacs 中查找东西（比如缓冲
区、文件等）时，它将帮助你导向正确的方向。

Helm 派生（ fork ）自 anything.el 。它致力于清理 anything.el 中的遗留代码并提供一个
更整洁、更精致以及更模块化的工具。

Helm 需要 Emacs 24.3 及以上版本。

* 特性
Helm （ Anything ），提供全新的 Emacs 使用体验。通常 Emacs 的使用方式是指定一个
操作然后选择操作对象， Helm （ Anything ）的方式是先选择一个操作对象然后对这个对
象执行操作。

** 补全
Helm 的 minibuffer 补全与 Emacs 缺省的补全有些许不同。

1) Emacs 缺省的补全是以 minibuffer 为中心的（ minibuffer centric ）。
   当在 minibuffer 输入并按 `TAB` 之后，Emacs 会转化你在 minibuffer 的输入（比如，
   将所有候选项共同的，但你没有完全输入的部分补到你的输入之后）帮助你精炼你的选
   择项，然后你可以继续输入并通过 `TAB` 来精炼，最后，minibuffer 的内容符合你的
   预期之后，按 `ENT` 选择执行。
2) Helm 的补全则是补全窗口为中心的（ completion window centric）。
   你不需要关注 minibuffer ，只需要关注补全窗口和里面的当前高亮项。随着你的输入，
   补全窗口候选项列表会更精炼，直到你需要的候选项足够接近当前高亮项时，你可以通
   过 `C-n` 移动高亮条，将它高亮并用 `ENT` 来选择它。

* 使用
#+BEGIN_SRC elisp
;; Load Helm package
(require 'helm-config)

(helm-mode 1)
#+END_SRC

在使用中，可以通过 `M-x helm-mode` 来开关 helm mode 。

* 参考
[[http://www.emacswiki.org/emacs/Helm][EmacsWiki: Helm]]
[[https://github.com/emacs-helm/helm][emacs-helm/helm · GitHub]]

