# -*- mode: org; coding: utf-8; -*-

#+OPTIONS:	\n:t
#+TITLE: 使用 Emacs
#+AUTHOR: Liu Hui
#+EMAIL: hliu@arcsoft.com

* 术语
window
buffer
frame
prefix arg

* Shell
M-! cmd <RET> 或者 M-x shell-command
运行 cmd ，输出显示到 \*Shell Command Output\* 缓冲区。

M-| cmd <RET> 或者 M-x shell-command-on-region
运行 cmd ，以当前 buffer 选区内容作为输入，

M-& cmd <RET> 或者 M-x async-shell-command
异步运行 cmd ，输出显示到 \*Async Shell Command\* 缓冲区。

M-x shell

M-x term

M-x eshell

* Help
`C-h c <key>` 在回显区（ echo area ）显示快捷键绑定的命令
`C-h k <key>` 查看快捷键绑定。
`C-h K <key>` 查看 Emacs 手册中关于快捷键绑定命令的段落。
`C-h b` 查看当前上下文所有快键绑定。
`C-h f <function>` 查看函数。
`C-h w <command>` 查看特定命令绑定的快捷键。
`C-h v <variable>` 查看变量说明及当前值。
`C-h m` 查看当前上下文的所有模式（ Major 和 Minor ）的快捷键绑定。
`C-h l` 查看最近的 300 个键输入（包括键盘，鼠标及菜单）。
`C-h L <language>` 查看语言环境（ language environment ）。
`C-h C <coding>` 查看编码系统（ coding system ）
`C-h I <input method>` 查看输入方法（ input method ）
`C-h P <package>` 查看软件包（ package ）

* 菜单（ Menu bar ）
GUI 程序可以使用鼠标， <F10> 或者命令 menu-bar-open 操作菜单。
终端下使用 M-` （ ESC-` ）， <F10> 或者命令 tmm-menubar 操作菜单。

* 补全（ Completion ）

补全在 Emacs 可以表示不同的东西。特别来说，它指在 minibuffer 中的输入补全及非 minibuffer
缓冲区中的文本补全。 minibuffer 中的输入可以是 `M-x` 后输入的命令或者响应 minibuffer 中提示
所输入的文本。

** 补全规则

*** emacs21
*** emacs22
*** basic
*** partial-completion
*** substring
*** initials

原生 Emacs 的 `basic` 补全规则，补全候选项是前缀与输入相匹配的哪些项。比如，输入
`M-x region TAB` ，将显示所有以 `region` 开头的命令。原生 Emacs 在版本 23 之前，
只有严格的前缀补全规则。版本 23 开始，使用了多种补全规则，你可以通过 `completion-styles`
参数来指定使用哪些规则，它的值是一个列表，列表里的每一项都是一个补全规则，补全的时候将按照顺序来
匹配，默认的值是 (basic partial-completion emacs22) ，不过，很多 Emacs 命令会忽略这个
参数。 只有在前一个规则下没有得到任何候选项的情况下，才会匹配后一个规则。
你输入 `when` ，不会得到 `eval-when-compile` 的候选项。？？？？


** Minibuffer 输入补全

** 缓冲区内的文本补全
