# -*- mode: org; coding: utf-8; -*-
#+OPTIONS: \n:t
#+OPTIONS: ^:nil
#+TITLE:	Emacs 之 CEDET
#+AUTHOR: Liu Hui
#+EMAIL: hliu@arcsoft.com
#+LATEX_CLASS: cn-article
#+LATEX_CLASS_OPTIONS: [9pt,a4paper]
#+LATEX_HEADER: \usepackage{geometry}
#+LATEX_HEADER: \geometry{top=2.54cm, bottom=2.54cm, left=3.17cm, right=3.17cm}
#+latex_header: \makeatletter
#+latex_header: \renewcommand{\@maketitle}{
#+latex_header: \newpage
#+latex_header: \begin{center}%
#+latex_header: {\Huge\bfseries \@title \par}%
#+latex_header: \end{center}%
#+latex_header: \par}
#+latex_header: \makeatother

#+LATEX: \newpage

* 概述
CEDET （ Collection of Emacs Development Environment Tools ） http://cedet.sourceforge.net/ 是一个工具集，目标是在 Emacs 里创建一个高级开发环境。

* 组成
它包含以下几个主要的组件：

** Semantic
  一个基于语法分析器（ Parser ）的文本分析的框架。它是一个词法分析器（ lexer ），一个语法分析器的生成器，同时也是一个语法分析器。
Semantic 的目的是为希望以通用方式处理各种语言，跟特定语言无关的语言工具作者提供一个中间层（ intermediate ）的 API ，
同样的，它也为身为语言专家的语言模式（ Mode ）作者提供一种简单的方式来编写供语言工具使用的语言分析器，他们也不需要这些语言工具的细节。
为从代码萃取的信息提供通用的表述，如此，其他的包（比如 JDEE 或 ECB ）可以实现现代开发环境所需的功能 - 代码补全，代码导航（代码跳转）等等。
*** SemanticDB
*** Bovine / Wisent
  Bovine （ original semantic LL parser ）
  Wisent （ Bison-like LALR parser ）
** Senator
  使用 Semantic 从代码中萃取的信息实现在代码中的导航。
** SRecode （ Semantic Recoder ）
  模板管理系统，使用语法信息或者 Semantic 标记 （ tags ） 生成代码。
** EDE (Emacs Development Environment: A project management system)
  通过一系列的扩展实现了一个类似于其他 IDE 的开发环境来管理项目。提供不同于 Emacs 本身提供的调试、编译等命令，并和项目管理命令一起集成到一个简单的菜单中。此外，使用项目的概念，可以更精确进行基于 Semantic 的操作。
** Speedbar
  在一个专门的帧（ Frame ）显示当前缓冲区的相关信息，它们来自于不同的信息源 - Semantic ，其他专门信息的提供者（比如 texinfo 和 HTML ）。
** EIEIO
** Cogre
  在 Emacs 中生成类似 UML 图表的库，与 Semantic 集成。

